version: '3.8'

networks:
  default:

services:
  db:
    image: mysql:8.1.0
    container_name: bangalore_blues_db
    ports:
      - 3306-3306
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bangalore_blues_db
