package com.sleek.scrapper.nobroker;

public enum PropertyAttribute {
    PROPERTY_AGE("propertyAge"),
    PARKING("parking"),
    PARKING_DESC("parkingDesc"),
    SHORTLISTED_BY_LOGGED_IN_USER("shortlistedByLoggedInUser"),
    LAST_UPDATE_DATE("lastUpdateDate"),
    FURNISHING_DESC("furnishingDesc"),
    BALCONIES("balconies"),
    CUP_BOARD("cupBoard"),
    LOCALITY_TRUNCATED("localityTruncated"),
    NEGOTIABLE("negotiable"),
    TYPE("type"),
    OWNER_ID("ownerId"),
    RENT("rent"),
    AVAILABLE_FROM("availableFrom"),
    PHOTOS("photos"),
    PROPERTY_SIZE("propertySize"),
    LOAN_AVAILABLE("loanAvailable"),
    ORIGINAL_IMAGE_URL("originalImageUrl"),
    ACCOMODATION_TYPE_DESC("accomodationTypeDesc"),
    ID("id"),
    STATE("state"),
    LOCALITY_ID("localityId"),
    ADMIN_EVENT("adminEvent"),
    LAST_UPDATE_STRING("lastUpdateString"),
    BATHROOM("bathroom"),
    PROPERTY_TITLE("propertyTitle"),
    POWER_BACKUP("powerBackup"),
    LONGITUDE("longitude"),
    DATE_ONLY("dateOnly"),
    BUYER_PROPERTY("buyerProperty"),
    ACTIVATE_LATER("activateLater"),
    INDEX_NAME("indexName"),
    SEO_DESCRIPTION("seoDescription"),
    INACTIVE_REASON("inactiveReason"),
    LOCALITY("locality"),
    ACTIVE("active"),
    MAINTENANCE_AMOUNT("maintenanceAmount"),
    CREATION_DATE("creationDate"),
    SWIMMING_POOL("swimmingPool"),
    WATER_SUPPLY("waterSupply"),
    PROPERTY_SCORE("propertyScore"),
    COMPLETE_STREET_NAME("completeStreetName"),
    ACCURATE_LOCATION("accurateLocation"),
    PIN_CODE("pinCode"),
    FILTER_PREFERENCE_SCORE("filterPreferenceScore"),
    TOTAL_FLOOR("totalFloor"),
    MAPPED("mapped"),
    LIFT("lift"),
    DEPOSIT("deposit"),
    GYM("gym"),
    DETAIL_URL("detailUrl"),
    REACTIVATION_SOURCE("reactivationSource"),
    ACTIVATION_DATE("activationDate"),
    FACING_DESC("facingDesc"),
    OWNER_DESCRIPTION("ownerDescription"),
    LEASE_TYPE_NEW("leaseTypeNew"),
    FURNISHING("furnishing"),
    AMENITIES("amenities"),
    PHOTO_AVAILABLE("photoAvailable"),
    TYPE_DESC("typeDesc"),
    CITY("city"),
    SHORT_URL("shortUrl"),
    LATITUDE("latitude"),
    PROMOTED_B("promoted_b"),
    REACTIVATION_REQ_DATE("reactivationReqDate"),
    FACING("facing"),
    TITLE("title"),
    NB_LOCALITY("nbLocality"),
    LEASE_TYPE("leaseType"),
    SOCIETY("society"),
    PREMIUM("premium"),
    OWNER_NAME("ownerName"),
    STREET("street"),
    PROPERTY_TYPE("propertyType"),
    SECONDARY_TITLE("secondaryTitle"),
    AEA__("aea__"),
    FLOOR("floor"),
    THUMBNAIL_IMAGE("thumbnailImage"),
    SHOW_REQUEST_PHOTO("showRequestPhoto"),
    LAST_ACTIVATION_DATE("lastActivationDate"),
    FOR_LEASE("forLease"),
    ADDRESS("address"),
    INACTIVE_REASON_DESC("inactiveReasonDesc"),
    SPONSORED("sponsored"),
    DOCUMENT_NAME("documentName"),
    PROPERTY_TITLE_TRUNCATED("propertyTitleTruncated"),
    VIDEO_UNIT("videoUnit"),
    URL("url"),
    FORMATTED_PRICE("formattedPrice"),
    COLOUR("colour"),
    TENANT_TYPE_DESC("tenantTypeDesc"),
    AMENITIES_MAP("amenitiesMap"),
    LOCATION("location"),
    MAINTENANCE("maintenance"),
    SHARED_ACCOMODATION("sharedAccomodation"),
    BUILDING_TYPE("buildingType"),
    PROJECT_URL("projectUrl"),
    PROPERTY_CODE("propertyCode"),
    LISTING_VERIFIED("listingVerified"),
    BUILDING_ID("buildingId"),
    SHOW_PROJECT("showProject"),
    HIGH_LIGHTS("highLights"),
    LISTING_NUDGE("listingNudge"),
    SCORE("score"),
    VERIFIED_BY_USER("verifiedByUser");

    private final String attribute;
    PropertyAttribute(final String attribute) {
        this.attribute = attribute;
    }

    public PropertyAttribute getPropertyAttribute(final String attribute) {
        return PropertyAttribute.valueOf(attribute);
    }

    public String getString() {
        return attribute;
    }
}
